# Read the Docs configuration file
# This schema uses https://github.com/23andMe/Yamale
# for the validation.
# Default values are indicated with a comment (``Default: ...``).
# Some values are default to the project config (settings from the web panel).

# The version of the spec to be use
version: 2

# Formats of the documentation to be built
# Default: []
formats:
   - htmlzip

# Configuration for the documentation build process
build:
   image: latest

# Configuration of the Python environment to be used
python:
   version: 3
   install:
      - method: setuptools
        path: src/pyart/
      - method: setuptools
        path: src/pyrad/

conda:
   # The path to the Conda environment file from the root of the project
   environment: ./src/pyrad_proc/continuous_integration/conda_environment-basic.yml

build:
   image: latest

sphinx:
   builder: html
   configuration: ./doc/pyrad/library_reference_users/source/conf.py
   fail_on_warning: false

submodules:
   include: all