language: python

addons:
    apt:
        packages:
        - gfortran

matrix:
    include:
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - PYTHON_VERSION="3.7"

# command to install dependencies
install:
   - source src/pyrad_proc/continuous_integration/install.sh

# command to run tests
script:
   - python -c "import pyart; pyart._debug_info()"
   - python -c "import pyrad"
#   - if [[ "$PYTHON_VERSION" != "3.5" ]]; then python -c "import wradlib; wradlib.__version__"; fi # commented because of issues with library liboppler.so.76 in wradlib
#  - pytest # or py.test for Python versions 3.5 and below
after_failure:
   - conda info
   - conda list
after_success:
   - conda info
   - conda list
