language: python
python:
  - "3.5"
  - "3.6"

addons:
    apt:
        packages:
        - gfortran

# command to install dependencies
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # creation of conda environment and installation of dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # Dependencies installation:
  # Py-ART required dependencies
  - conda install -c conda-forge netcdf4

  # Py-ART optional dependencies
  - conda install -c conda-forge h5py pytest basemap cartopy gdal
  - conda install -c https://conda.binstar.org/jjhelmus trmm_rsl
  - conda install -c conda-forge wradlib
  - conda install -c conda-forge "poppler<0.61"
  - pip install --trusted-host pypi.python.org xmltodict

  # Pyrad required dependencies
  - conda install -c conda-forge pandas shapely

  # Pyrad optional dependencies
  - conda install -c conda-forge dask bokeh memory_profiler

  # export global variables
  - export RSL_PATH="$HOME/miniconda/envs/test-environment"
  - export GDAL_DATA="$HOME/miniconda/share/gdal"
  # - export PYART_CONFIG="$HOME/pyrad/config/pyart/mch_config.py"
  # - export METRANETLIB_PATH=""

  # installation of pyart and pyrad
  - cd src/pyart
  - python setup.py install --user
  - cd ../pyrad_proc
  - python setup.py install --user
  - cd

# command to run tests
script:
   - python -c "import pyart; pyart._debug_info()"
   - python -c "import wradlib; wradlib.__version__"
   - python -c "import pyrad"
   - conda list
#  - pytest # or py.test for Python versions 3.5 and below
