language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # creation of conda environment and installation of dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install netcdf4 h5py nose pandas
  - conda install -c conda-forge basemap cartopy gdal
  - conda install -c https://conda.binstar.org/jjhelmus trmm_rsl
  - conda install -c conda-forge wradlib
  - pip install --trusted-host pypi.python.org xmltodict

  # export global variables
  - export RSL_PATH="$HOME/miniconda"
  - export GDAL_DATA="$HOME/miniconda/share/gdal"
  # - export PYART_CONFIG="$HOME/pyrad/config/pyart/mch_config.py"
  # - export METRANETLIB_PATH=""

  # installation of pyart and pyrad
  - cd src/pyart
  - python setup.py install --user
  - cd ../pyrad
  - python setup.py install --user

# command to run tests
#script:
#  - pytest # or py.test for Python versions 3.5 and below
