name: Test pyrad base
env:
  MINIMAL_DEPENDENCIES: Cython numpy cartopy
  TEST_DEPENDENCIES: pytest imageio pygrib

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      max-parallel: 6

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
         ref : master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install dependencies
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/environment-ci.yml
          activate-environment: pyrad-dev
          cache-downloads: true
          python-version: ${{ matrix.python-version }}
      - name: Clone pyart
        uses: actions/checkout@master
        with:
          repository: ARM-DOE/pyart
          path: pyart
      - name: Clone pyrad-tests
        uses: actions/checkout@master
        with:
          repository: MeteoSwiss/pyrad-tests
          path: pyrad-tests
      - name: Install pyart
        working-directory:  ${{github.workspace}}/pyart/
        run: python -m pip install .
      - name: Install pyrad
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}/src/pyrad_proc/
        run: python -m pip install .

      - name: Check imports
        working-directory: ${{github.workspace}}/pyrad-tests/
        run: |
          python -c "import pyrad; print(pyrad.__file__)"
          python -c "from pyrad.flow import main"
      - name: Run tests
        env:
            S3_SECRET_READ: ${{ secrets.S3_SECRET_READ }}
            S3_KEY_READ: ${{ secrets.S3_KEY_READ }}
            S3_SECRET_WRITE: ${{ secrets.S3_SECRET_WRITE }}
            S3_KEY_WRITE: ${{ secrets.S3_KEY_WRITE }}
            PYRAD_TESTS_PATH: ${{github.workspace}}/pyrad-tests/
        working-directory: ${{github.workspace}}/pyrad-tests/
        run: pytest "run_tests.py::test_base"
