name: Test pyrad
env:
  MINIMAL_DEPENDENCIES: cython numpy scipy dask netCDF4
  OPTIONAL_DEPENDENCIES: pyfftw cartopy h5py PyWavelets pandas scikit-image
  TEST_DEPENDENCIES: pytest pytest-cov

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.6", "3.7", "3.8"]
      max-parallel: 6

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: flexible
          activate-environment: test-environment

      - name: Install dependencies
        env:
          PACKAGES: ${{env.MINIMAL_DEPENDENCIES}} ${{env.OPTIONAL_DEPENDENCIES}} ${{env.TEST_DEPENDENCIES}}
          PYRAD_EXAMPLES_PATH: ${{github.workspace}}/pyrad-examples/
        run: |
          conda install --quiet ${{env.PACKAGES}}
          pip install -U cookiecutter
      - name: Install pyart
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}/src/pyart/
        run: pip install .
      - name: Install pyrad
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}/src/pyrad_proc/
        run: pip install .
      - name: Download pyrad-examples
        env:
          PYRAD_EXAMPLES_PATH: ${{github.workspace}}/pyrad-examples/
        working-directory: ${{github.workspace}}/ci
        run: python fetch_pyrad_examples.py

      - name: Check imports
        working-directory: ${{github.workspace}}/pyrad-examples/
        run: |
          python -c "import pyrad; print(pyrad.__file__)"
          python -c "from pyrad.flow import main"
      - name: Run tests
        env:
           PYRAD_EXAMPLES_PATH: ${{github.workspace}}/pyrad-examples/
        working-directory: ${{github.workspace}}/src/pyrad_proc/tests/
        run: pytest run_tests.py
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: daniel.wolfensberger@meteoswiss.ch
          # from email name
          from: Daniel Wolfensberger
    
