name: Test pyrad base dev
env:
  MINIMAL_DEPENDENCIES: Cython numpy cartopy
  TEST_DEPENDENCIES: pytest pygrib  imageio

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" , "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      max-parallel: 6

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
         ref : dev
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone pyart
        uses: actions/checkout@master
        with:
          repository: ARM-DOE/pyart 
          path: pyart
      - name: Clone pyrad-tests
        uses: actions/checkout@master
        with:
          repository: MeteoSwiss/pyrad-tests
          path: pyrad-tests
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          init-shell: >-
            bash
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: flexible
          activate-environment: test-environment

      - name: Install dependencies
        env:
          PACKAGES: ${{env.MINIMAL_DEPENDENCIES}} ${{env.OPTIONAL_DEPENDENCIES}} ${{env.TEST_DEPENDENCIES}}
          PYRAD_TESTS_PATH: ${{github.workspace}}/pyrad-tests/
        run: |
          conda install --quiet ${{env.PACKAGES}}
          pip install wradlib
      - name: Install pyart
        working-directory:  ${{github.workspace}}/pyart/
        run: python -m pip install .
      - name: Install pyrad
        if: matrix.os != 'macos-latest'
        working-directory: ${{github.workspace}}/src/pyrad_proc/
        run: python -m pip install .

      - name: Check imports
        working-directory: ${{github.workspace}}/pyrad-tests/
        run: |
          python -c "import pyrad; print(pyrad.__file__)"
          python -c "from pyrad.flow import main"
      - name: Run tests
        env:
           PYRAD_TESTS_PATH: ${{github.workspace}}/pyrad-tests/
        working-directory: ${{github.workspace}}/pyrad-tests/
        run: pytest "run_tests.py::test_base"
      - name: tmate session if tests fail
        if:  ${{ github.event_name == 'workflow_dispatch' && failure() }}
        uses: mxschmitt/action-tmate@v3
        
