name: test_ruff

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This job installs dependencies, build the website, and pushes it to `gh-pages`
jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    if: github.repository == 'MeteoSwiss/pyrad'
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu]

    steps:
      - uses: actions/checkout@v2

      - name: Run Linting
        working-directory: ${{github.workspace}}/src/pyrad_proc/pyrad/
        shell: bash -l {0}
        run: |
          pip install ruff
          ruff check --ignore E501 . 
